server:
  port: 8080
  # graceful shutdown makes sure we have time to finnish any ongoing rest requests before terminating
  # default value will be 30s before terminating
  shutdown: graceful

spring:
  threads:
    virtual:
      enabled: true #To enable virtual threads in Spring Boot 3.2 we just need to set this property
  application:
    name: authentication
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    hikari.connectionTimeout: 100000
    hikari.idleTimeout: 600000
    hikari.maxLifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: create-drop = none

# To access in memory database console : http://localhost:8080/h2   
  h2:
    console:
      enabled: true
      path: /h2	  
      settings:
        trace: false
        web-allow-others: false
           
  liquibase:
    enabled: false
    change-log: classpath:db/changelog-master.xml

springdoc:
  api-docs:
    path: /authentication-docs
  swagger-ui:
    path: /authentication-docs/swagger-ui-custom.html

logging.level:
  root: INFO
  liquibase: INFO