CREATE TABLE CITY(
	CITY_ID INT AUTO_INCREMENT,
	CITY_NAME VARCHAR(100),

	CONSTRAINT PK_CITY_ID PRIMARY KEY (CITY_ID)
);


CREATE TABLE PERSONS(
    PERSON_ID INT AUTO_INCREMENT,
    CITY_ID INT,
    FIRST_NAME VARCHAR(10),
    LAST_NAME VARCHAR(64),
    EMAIL VARCHAR(64),
    
    CONSTRAINT PK_PERSON_ID PRIMARY KEY(PERSON_ID),
    CONSTRAINT FK_CITY_ID FOREIGN KEY(CITY_ID) REFERENCES CITY (CITY_ID)
);


CREATE TABLE PERSON_IDENTITY(
    PERSON_IDENTITY_ID INT AUTO_INCREMENT,
    PERSON_IDENTITY_NAME VARCHAR(100),
    
    PERSON_ID INT,
    
    CONSTRAINT PK_PERSON_IDENTITY_ID PRIMARY KEY(PERSON_IDENTITY_ID),
    CONSTRAINT FK_PERSON_ID FOREIGN KEY(PERSON_ID) REFERENCES PERSONS (PERSON_ID)
);

