CREATE SEQUENCE "CITY_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1;
CREATE TABLE CITY(
	CITY_ID NUMBER(9, 0),
	CITY_NAME VARCHAR2(100),

	CONSTRAINT "PK_CITY_ID" PRIMARY KEY ("CITY_ID")
);

CREATE SEQUENCE "PERSON_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1;
CREATE TABLE PERSONS(
    PERSON_ID NUMBER(9,0),
    CITY_ID NUMBER(9, 0),
    FIRST_NAME VARCHAR2(10),
    LAST_NAME VARCHAR2(64),
    EMAIL VARCHAR2(64),
    CONSTRAINT "PK_PERSON_ID" PRIMARY KEY("PERSON_ID"),
    CONSTRAINT "FK_CITY_ID" FOREIGN KEY("CITY_ID") REFERENCES "CITY" ("CITY_ID") ENABLE
);

CREATE SEQUENCE "PERSON_IDENTITY_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1;
CREATE TABLE PERSON_IDENTITY(
    PERSON_IDENTITY_ID NUMBER(9,0),
    PERSON_IDENTITY_NAME VARCHAR2(100),
    
    PERSON_ID NUMBER(9,0),
    
    CONSTRAINT "PK_PERSON_IDENTITY_ID" PRIMARY KEY("PERSON_IDENTITY_ID"),
    CONSTRAINT "FK_PERSON_ID" FOREIGN KEY("PERSON_ID") REFERENCES "PERSONS" ("PERSON_ID") ENABLE
);

